apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: mem-stress
  namespace: default
spec:
  mode: all
  selector:
    namespaces:
      - default  
  stressors:
    memory:
      workers: 4
      size: 50MiB
      options: ['']
  duration: '1h'