apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-charts.fullname" . }}
  labels:
    app.kubernetes.io/instance: first-deploy
    app.kubernetes.io/name: helm-charts
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: first-deploy
      app.kubernetes.io/name: helm-charts
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/instance: first-deploy
        app.kubernetes.io/name: helm-charts

    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              cpu: "10m" # Set an appropriate value
              memory: "128Mi" # Set an appropriate value
            limits:
              cpu: "50m"
              memory: "256Mi" 
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: frontend-files
              mountPath: /app
      volumes:
        - name: frontend-files
          hostPath:
            path: /files
