apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-charts.fullname" . }}
  labels:
    {{- include "helm-charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              cpu: "10m" # Set an appropriate value
              memory: "128Mi" # Set an appropriate value
            limits:
              cpu: "50m"
              memory: "256Mi" 
          volumeMounts:
            - name: frontend-files
              mountPath: /app
      volumes:
        - name: frontend-files
          hostPath:
            path: /files
