apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm-charts.fullname" . }}-ingress
  annotations:
    # Add annotations for the Ingress Controller if required
spec:
  rules:
    - host: first-deploy.com  # Replace with your desired hostname
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "helm-charts.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
