apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm-charts.fullname" . }}-ingress
  annotations:

spec:
  rules:
    - host: first-deploy.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "helm-charts.fullname" . }}
              port:
                number: {{ .Values.service.port }}

