name: CI/CD using Helm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.20.0'
    
    - name: Install Helm
      run: |
        curl -LO "https://get.helm.sh/helm-v3.5.2-linux-amd64.tar.gz"
        tar -zxvf helm-v3.5.2-linux-amd64.tar.gz
        sudo mv linux-amd64/helm /usr/local/bin/helm
      
    - name: Deploy with Helm
      run: |
        helm upgrade --install my-release ./helm-charts

