name: CI with Minikube
on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start Minikube
      run: |
        minikube start --driver=docker

    - name: Check pods
      run: |
        kubectl get pods -n kube-system

    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./docker/Dockerfile -t local/example .
        echo -n "verifying images:"
        docker images         

    # Add your deployment and test steps here.
    # e.g., helm install, kubectl apply, etc.
