name: CI with Minikube

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start Minikube
      run: |
        minikube start --driver=docker

    - name: Check pods
      run: |
        kubectl get pods -n kube-system

    # Add your deployment and test steps here.
    # e.g., helm install, kubectl apply, etc.
