name: CI with Minikube
on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start Minikube
      run: |
        minikube start --driver=docker

    - name: Check pods
      run: |
        kubectl get pods -n kube-system

    - name: Install Helm
      run: |
        curl -LO "https://get.helm.sh/helm-v3.5.2-linux-amd64.tar.gz"
        tar -zxvf helm-v3.5.2-linux-amd64.tar.gz
        sudo mv linux-amd64/helm /usr/local/bin/helm        

    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./docker/Dockerfile -t local/example .
        echo -n "verifying images:"
        docker images 
        docker run -d -p 80:80 local/example 
        docker logs $(docker ps -aqf "ancestor=local/example")
        docker ps -a   
        for i in {1..10}; do
            if curl localhost:80; then
                break
            fi
            sleep 5
        done

    # Add your deployment and test steps here.
    # e.g., helm install, kubectl apply, etc.
